### ISSUE TITLE
dellos9_config failing

### ISSUE THREAD

**Issue by wilshire461** [Dell-Networking/ansible-dellos-examples#2]
We have 13 s3038 and 1 s4048 switch here.  All but one of the s3048 will allow dellos9_config to actually run and apply changes.  On all other hosts with the same Switch OS software and the module runs into a python syntax error.

You can see the errors in the below output, sn-hpcf-rcswe4-1 is the host that does accept the dellos9_config changes,  sn-hpcf-rcswe4-2 is an example of a switch that encounters python syntax errors.

```
# ssh admin@sn-hpcf-rcswe4-2
sn-hpcf-rcswe4-2>show version
Dell Real Time Operating System Software
Dell Operating System Version:  2.0
Dell Application Software Version:  9.10(0.1P3)
Copyright (c) 1999-2016 by Dell Inc. All Rights Reserved.
Build Time: Tue Jun 14 15:00:23 2016
Build Path: /sites/eqx/work/swbuild01_1/build06/E9-10-0/SW/SRC
Dell Networking OS uptime is 6 week(s), 5 day(s), 3 hour(s), 15 minute(s)

System image file is "system://A"

System Type: S3048-ON 
Control Processor: Intel Rangeley with 2 Gbytes (2127654912 bytes) of memory, core(s) 2.

8G bytes of boot flash memory.

  1 52-port GE/TE (SG-ON)
 48 GigabitEthernet/IEEE 802.3 interface(s)
  4 Ten GigabitEthernet/IEEE 802.3 interface(s)
sn-hpcf-rcswe4-2>show version
```
```
# ssh admin@sn-hpcf-rcswe4-1


 The SupportAssist EULA acceptance option has not been selected. SupportAssist
 can be enabled once the SupportAssist EULA has been accepted. Use the:
 'support-assist activate' command to accept EULA and enable SupportAssist.

sn-hpcf-rcswe4-1#show version
Dell Real Time Operating System Software
Dell Operating System Version:  2.0
Dell Application Software Version:  9.10(0.1P3)
Copyright (c) 1999-2016 by Dell Inc. All Rights Reserved.
Build Time: Tue Jun 14 15:00:23 2016
Build Path: /sites/eqx/work/swbuild01_1/build06/E9-10-0/SW/SRC
Dell Networking OS uptime is 6 week(s), 5 day(s), 3 hour(s), 16 minute(s)

System image file is "system://A"

System Type: S3048-ON 
Control Processor: Intel Rangeley with 2 Gbytes (2127654912 bytes) of memory, core(s) 2.

8G bytes of boot flash memory.

  1 52-port GE/TE (SG-ON)
 48 GigabitEthernet/IEEE 802.3 interface(s)
  4 Ten GigabitEthernet/IEEE 802.3 interface(s)
sn-hpcf-rcswe4-1#
```

Working host sn-hpcf-rcswe4-1 dellos9_config output
```
# ansible-playbook -i Summit-switches summit-configure.yaml -e 'ansible_python_interpreter="/usr/bin/env python"' -vvv --ask-vault-pass --tags switch-config-check --limit test
Using /home/jobl6604/dev/ansible-networking/ansible.cfg as config file
Vault password: 

PLAYBOOK: summit-configure.yaml ************************************************
1 plays in summit-configure.yaml

PLAY [summit-switches] *********************************************************
/home/jobl6604/ansible_venv/python-2.7.13/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

TASK [check configuration] *****************************************************
task path: /home/jobl6604/dev/ansible-networking/summit-configure.yaml:16
Using module file /home/jobl6604/ansible_venv/python-2.7.13/lib/python2.7/site-packages/ansible/modules/core/network/dellos9/dellos9_config.py
<192.168.224.70> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.224.70> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722 `" && echo ansible-tmp-1487621769.39-57146327494722="` echo $HOME/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722 `" ) && sleep 0'
<192.168.224.70> PUT /tmp/tmpCxzygi TO /root/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722/dellos9_config.py
<192.168.224.70> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722/ /root/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722/dellos9_config.py && sleep 0'
<192.168.224.70> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722/dellos9_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487621769.39-57146327494722/" > /dev/null 2>&1 && sleep 0'
changed: [sn-hpcf-rcswe4-1] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": [
                "Current Configuration ...\n! Version 9.10(0.1P3)\n! Last configuration change at Sat Feb 18 05:30:10 2017 by rcops\n! Startup-config last updated at Sat Feb 18 05:30:16 2017 by rcops\n!\nboot system stack-unit 1 primary system://A\nboot system stack-unit 1 secondary system://B\n!\nhostname sn-hpcf-rcswe4-1\n!\nprotocol lldp \n!\nredundancy auto-synchronize full\n!\nusername rcops password 7 381e189bf323bdf2 privilege 15 \nusername admin nopassword privilege 15\n!\ndefault vlan-id 3100\n!\nstack-unit 1 provision S3048-ON\n!\ninterface GigabitEthernet 1/1\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/2\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/3\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/4\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/5\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/6\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/7\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/8\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/9\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/10\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/11\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/12\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/13\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/14\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/15\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/16\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/17\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/18\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/19\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/20\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/21\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/22\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/23\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/24\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/25\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/26\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/27\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/28\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/29\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/30\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/31\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/32\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/33\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/34\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/35\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/36\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/37\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/38\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/39\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/40\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/41\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/42\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/43\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/44\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/45\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/46\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/47\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface GigabitEthernet 1/48\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface TenGigabitEthernet 1/49\n no ip address\n!  \n port-channel-protocol LACP \n  port-channel 2 mode active \n no shutdown\n!\ninterface TenGigabitEthernet 1/50\n no ip address\n!  \n port-channel-protocol LACP \n  port-channel 2 mode active \n no shutdown\n!\ninterface TenGigabitEthernet 1/51\n no ip address\n shutdown\n!\ninterface TenGigabitEthernet 1/52\n no ip address\n shutdown\n!\ninterface ManagementEthernet 1/1\n ip address 172.16.42.70/20\n no shutdown\n!\ninterface ManagementEthernet 2/1\n no shutdown\n!\ninterface ManagementEthernet 3/1\n no shutdown\n!\ninterface ManagementEthernet 4/1\n shutdown\n!\ninterface ManagementEthernet 5/1\n shutdown\n!\ninterface ManagementEthernet 6/1\n shutdown\n!\ninterface Port-channel 2\n no ip address\n portmode hybrid\n switchport\n no shutdown\n!\ninterface Vlan 224\n ip address 192.168.224.70/26\n tagged Port-channel 2\n no shutdown\n!\ninterface Vlan 3100\n!untagged GigabitEthernet 1/1-1/48\n!untagged Port-channel 2\n!\ninterface Vlan 3108\n ip address 10.225.40.13/20\n tagged GigabitEthernet 1/1-1/48\n tagged Port-channel 2\n no shutdown\n!\nip route 0.0.0.0/0 192.168.224.65 \n!\nsnmp-server community private rw \nsnmp-server community public rw \n!\nno ip telnet server enable\n!\nip ssh server enable\n!\nline console 0\nline vty 0\nline vty 1\nline vty 2\nline vty 3\nline vty 4\nline vty 5\nline vty 6\nline vty 7\nline vty 8\nline vty 9\n!\nreload-type\n boot-type normal-reload\n config-scr-download enable\n!\nend"
            ], 
            "host": "192.168.224.70", 
            "lines": [
                "no ip telnet server enable", 
                "clock timezone MDT -13", 
                "ntp server 10.225.0.1"
            ], 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "host": "192.168.224.70", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": 30, 
                "transport": "cli", 
                "username": "admin"
            }, 
            "replace": "line", 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": 30, 
            "transport": "cli", 
            "update": "merge", 
            "username": "admin"
        }
    }, 
    "responses": [
        "", 
        "", 
        ""
    ], 
    "saved": false, 
    "updates": [
        "clock timezone MDT -13", 
        "ntp server 10.225.0.1"
    ]
}

PLAY RECAP *********************************************************************
sn-hpcf-rcswe4-1 : ok=1    changed=1    unreachable=0    failed=0   
```

Failing output from sn-hpcf-rcswe-4-2

```
# ansible-playbook -i Summit-switches summit-configure.yaml -e 'ansible_python_interpreter="/usr/bin/env python"' -vvv --ask-vault-pass --tags switch-config-check --limit sn-hpcf-rcswe4-2
Using /home/jobl6604/dev/ansible-networking/ansible.cfg as config file
Vault password: 

PLAYBOOK: summit-configure.yaml ************************************************
1 plays in summit-configure.yaml

PLAY [summit-switches] *********************************************************
/home/jobl6604/ansible_venv/python-2.7.13/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

TASK [check configuration] *****************************************************
task path: /home/jobl6604/dev/ansible-networking/summit-configure.yaml:16
Using module file /home/jobl6604/ansible_venv/python-2.7.13/lib/python2.7/site-packages/ansible/modules/core/network/dellos9/dellos9_config.py
<192.168.224.71> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.224.71> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464 `" && echo ansible-tmp-1487623204.97-11743101553464="` echo $HOME/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464 `" ) && sleep 0'
<192.168.224.71> PUT /tmp/tmp3mLbBz TO /root/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464/dellos9_config.py
<192.168.224.71> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464/ /root/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464/dellos9_config.py && sleep 0'
<192.168.224.71> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464/dellos9_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487623204.97-11743101553464/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_uA11Kd/ansible_module_dellos9_config.py", line 293, in <module>
    main()
  File "/tmp/ansible_uA11Kd/ansible_module_dellos9_config.py", line 255, in main
    config = get_config(module)
  File "/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/dellos9.py", line 43, in get_config
  File "/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 61, in get_config
  File "/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/dellos9.py", line 121, in get_config
  File "/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/shell.py", line 250, in execute
ansible.module_utils.network.NetworkError: matched error in response: show running-config
                      ^
% Error: Invalid input at "^" marker.


fatal: [sn-hpcf-rcswe4-2]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "lines": [
                "no ip telnet server enable", 
                "clock timezone MDT -13", 
                "ntp server 10.225.0.1"
            ], 
            "match": "line", 
            "provider": {
                "auth_pass": "BrcpwE23!", 
                "host": "192.168.224.71", 
                "password": "BrcpwE23!", 
                "timeout": 30, 
                "transport": "cli", 
                "username": "admin"
            }, 
            "update": "merge"
        }, 
        "module_name": "dellos9_config"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_uA11Kd/ansible_module_dellos9_config.py\", line 293, in <module>\n    main()\n  File \"/tmp/ansible_uA11Kd/ansible_module_dellos9_config.py\", line 255, in main\n    config = get_config(module)\n  File \"/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/dellos9.py\", line 43, in get_config\n  File \"/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/netcfg.py\", line 61, in get_config\n  File \"/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/dellos9.py\", line 121, in get_config\n  File \"/tmp/ansible_uA11Kd/ansible_modlib.zip/ansible/module_utils/shell.py\", line 250, in execute\nansible.module_utils.network.NetworkError: matched error in response: show running-config\r\n                      ^\r\n% Error: Invalid input at \"^\" marker.\r\n\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @/home/jobl6604/dev/ansible-networking/summit-configure.retry

PLAY RECAP *********************************************************************
sn-hpcf-rcswe4-2 : ok=0    changed=0    unreachable=0    failed=1  
```

Python version is 2.7.13
```# ansible --version
ansible 2.2.1.0
  config file = /home/jobl6604/dev/ansible-networking/ansible.cfg
  configured module search path = Default w/o overrides
```

Nothing changed in ansible.cfg from the default except ssh timeout was increased to 60 seconds.

**Comment by skg-net** [comment]
@wilshire461 Thanks for reporting the issue. We will re-simulate the issue, if any further info is required, will contact you.

Also, please note that supported OS9 version for Ansible is 9.10.0.1P13 or above. Basic playbook will work, but when you execute complex playbook on OS9 version prior to 9.10.0.1P13, will fail. Since the number of connection to the box is restricted 10 per minute. A cli command has been included in the patch ```ip ssh connection-rate-limit 60``` to increase the connection rate limit. Once the persistent ssh connection support is available from Ansible and Dell, prior version can be used.

Refer [Ansible Documentaion](https://docs.ansible.com/ansible/dellos9_config_module.html#notes)

**Comment by skg-net** [comment]
@wilshire461 We looked into the error, the users privilege level to access "show running config" is not there, that's the reason your are seeing that error If you look at the prompt of the failing device sn-hpcf-rcswe-4-2 ```sn-hpcf-rcswe4-2>show version``` . The prompt  `>` tells me that you are in Privilege level, where `show running-config` command is not available for the user.

Either your user needs to be at privileged level 15 or you need to set  ``` authorize: yes  auth_pass: xxxxx```  as part of your provider dict to execute the command in privileged mode.

Let me know if that resolves your issue.

Thanks,
@skg-net

**Comment by wilshire461** [comment]
@skg-net: thanks for the insight!  It turned out I neglected to include the `authorize` variable in the group variable file.  After setting that everything started working even with the older version of the OS.
