### ISSUE TITLE
socket_path does not exist or cannot be found

### ISSUE THREAD

**Issue by mvernimmen** [Dell-Networking/ansible-dellos-examples#8]
Hi,

When applying a playbook to create some port-channels on an s4148f with OS10, I keep getting this error:
```
fatal: [sw-06.us01]: FAILED! => {
    "changed": false,
    "err": "socket_path does not exist or cannot be found"
}

MSG:

unable to enter configuration mode
```

The playbook I'm applying is:
```
---
- name: test dell sw config
  hosts: sw-06.us01
  connection: network_cli

  tasks:
    - name: create port channels
      dellos10_config:
        lines:
        - interface port-channel 1
        - no shutdown
        - switchport mode trunk
        - switchport access vlan 1
        - vlt-port-channel 1

    - name: create port channels
      dellos10_config:
        lines:
        - interface port-channel {{ item }}
        - no shutdown
        - switchport mode trunk
        - switchport access vlan 1
        - vlt-port-channel {{ item }}
      loop:
        - 2
        - 3
```

Here is the very verbose output from the commands I've been trying to run:

```
# maxx @ MacBook-Pro-2 in ~/TK/ansible/dell-switches on git:master x [12:06:15] C:2
$ ansible-playbook -vvv -i inventory.yaml mve-pre-bonding.yaml
ansible-playbook 2.5.0
  config file = /Users/maxx/.ansible.cfg
  configured module search path = [u'/Users/maxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
Using /Users/maxx/.ansible.cfg as config file
Parsed /Users/maxx/TK/ansible/dell-switches/inventory.yaml inventory source with ini plugin

PLAYBOOK: mve-pre-bonding.yaml ***********************************************************************************************************************************************************************************************************************************************
1 plays in mve-pre-bonding.yaml

PLAY [test dell sw config] ***************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************
task path: /Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.yaml:2
Using module file /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/modules/system/setup.py
<sw-06.us01.textkernel.net> ESTABLISH LOCAL CONNECTION FOR USER: maxx
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066 `" && echo ansible-tmp-1524570660.1-278950133217066="` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066 `" ) && sleep 0'
<sw-06.us01.textkernel.net> PUT /Users/maxx/.ansible/tmp/ansible-local-15482GDas1F/tmprJ8A6C TO /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066/setup.py
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'chmod u+x /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066/ /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066/setup.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '/usr/bin/python /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066/setup.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'rm -f -r /Users/maxx/.ansible/tmp/ansible-tmp-1524570660.1-278950133217066/ > /dev/null 2>&1 && sleep 0'
ok: [sw-06.us01]
META: ran handlers

TASK [create port channels] **************************************************************************************************************************************************************************************************************************************************
task path: /Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.yaml:7
Using module file /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/modules/network/dellos10/dellos10_config.py
<sw-06.us01.textkernel.net> ESTABLISH LOCAL CONNECTION FOR USER: maxx
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151 `" && echo ansible-tmp-1524570663.76-280540794051151="` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151 `" ) && sleep 0'
<sw-06.us01.textkernel.net> PUT /Users/maxx/.ansible/tmp/ansible-local-15482GDas1F/tmpejen1R TO /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151/dellos10_config.py
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'chmod u+x /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151/ /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '/usr/bin/python /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'rm -f -r /Users/maxx/.ansible/tmp/ansible-tmp-1524570663.76-280540794051151/ > /dev/null 2>&1 && sleep 0'
fatal: [sw-06.us01]: FAILED! => {
    "changed": false,
    "err": "socket_path does not exist or cannot be found",
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "config": null,
            "host": null,
            "lines": [
                "interface port-channel 1",
                "no shutdown",
                "switchport mode trunk",
                "switchport access vlan 1",
                "vlt-port-channel 1"
            ],
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "update": "merge",
            "username": null
        }
    }
}

MSG:

unable to enter configuration mode

	to retry, use: --limit @/Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
sw-06.us01                 : ok=1    changed=0    unreachable=0    failed=1


# maxx @ MacBook-Pro-2 in ~/TK/ansible/dell-switches on git:master x [13:51:14] C:2
$ ansible-playbook -vvv -i inventory.yaml mve-pre-bonding.yaml --limit @/Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.retry
ansible-playbook 2.5.0
  config file = /Users/maxx/.ansible.cfg
  configured module search path = [u'/Users/maxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
Using /Users/maxx/.ansible.cfg as config file
Parsed /Users/maxx/TK/ansible/dell-switches/inventory.yaml inventory source with ini plugin

PLAYBOOK: mve-pre-bonding.yaml ***********************************************************************************************************************************************************************************************************************************************
1 plays in mve-pre-bonding.yaml

PLAY [test dell sw config] ***************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************
task path: /Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.yaml:2
Using module file /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/modules/system/setup.py
<sw-06.us01.textkernel.net> ESTABLISH LOCAL CONNECTION FOR USER: maxx
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467 `" && echo ansible-tmp-1524570727.29-32405431277467="` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467 `" ) && sleep 0'
<sw-06.us01.textkernel.net> PUT /Users/maxx/.ansible/tmp/ansible-local-15580PMYGtK/tmpt_KFcu TO /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467/setup.py
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'chmod u+x /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467/ /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467/setup.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '/usr/bin/python /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467/setup.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'rm -f -r /Users/maxx/.ansible/tmp/ansible-tmp-1524570727.29-32405431277467/ > /dev/null 2>&1 && sleep 0'
ok: [sw-06.us01]
META: ran handlers

TASK [create port channels] **************************************************************************************************************************************************************************************************************************************************
task path: /Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.yaml:7
Using module file /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/modules/network/dellos10/dellos10_config.py
<sw-06.us01.textkernel.net> ESTABLISH LOCAL CONNECTION FOR USER: maxx
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450 `" && echo ansible-tmp-1524570729.3-76645556750450="` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450 `" ) && sleep 0'
<sw-06.us01.textkernel.net> PUT /Users/maxx/.ansible/tmp/ansible-local-15580PMYGtK/tmpqbOO5H TO /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450/dellos10_config.py
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'chmod u+x /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450/ /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '/usr/bin/python /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'rm -f -r /Users/maxx/.ansible/tmp/ansible-tmp-1524570729.3-76645556750450/ > /dev/null 2>&1 && sleep 0'
changed: [sw-06.us01] => {
    "changed": true,
    "commands": [
        "interface port-channel 1",
        "no shutdown",
        "switchport mode trunk",
        "switchport access vlan 1",
        "vlt-port-channel 1",
        "commit"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "config": null,
            "host": null,
            "lines": [
                "interface port-channel 1",
                "no shutdown",
                "switchport mode trunk",
                "switchport access vlan 1",
                "vlt-port-channel 1"
            ],
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "update": "merge",
            "username": null
        }
    },
    "saved": false,
    "updates": [
        "interface port-channel 1",
        "no shutdown",
        "switchport mode trunk",
        "switchport access vlan 1",
        "vlt-port-channel 1",
        "commit"
    ]
}

TASK [create port channels] **************************************************************************************************************************************************************************************************************************************************
task path: /Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.yaml:16
Using module file /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/modules/network/dellos10/dellos10_config.py
<sw-06.us01.textkernel.net> ESTABLISH LOCAL CONNECTION FOR USER: maxx
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147 `" && echo ansible-tmp-1524570742.49-132600049626147="` echo /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147 `" ) && sleep 0'
<sw-06.us01.textkernel.net> PUT /Users/maxx/.ansible/tmp/ansible-local-15580PMYGtK/tmpfMiYXk TO /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147/dellos10_config.py
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'chmod u+x /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147/ /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c '/usr/bin/python /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147/dellos10_config.py && sleep 0'
<sw-06.us01.textkernel.net> EXEC /bin/sh -c 'rm -f -r /Users/maxx/.ansible/tmp/ansible-tmp-1524570742.49-132600049626147/ > /dev/null 2>&1 && sleep 0'
failed: [sw-06.us01] (item=2) => {
    "changed": false,
    "err": "socket_path does not exist or cannot be found",
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "config": null,
            "host": null,
            "lines": [
                "interface port-channel 2",
                "no shutdown",
                "switchport mode trunk",
                "switchport access vlan 1",
                "vlt-port-channel 2"
            ],
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "update": "merge",
            "username": null
        }
    },
    "item": 2
}

MSG:

unable to enter configuration mode

The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 104, in run
    item_results = self._run_loop(items)
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 322, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 554, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/dellos10_config.py", line 47, in run
    result = super(ActionModule, self).run(tmp, task_vars)
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/dellos10.py", line 86, in run
    out = conn.get_prompt()
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/module_utils/connection.py", line 140, in __rpc__
    response = self._exec_jsonrpc(name, *args, **kwargs)
  File "/usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible/module_utils/connection.py", line 115, in _exec_jsonrpc
    raise ConnectionError('socket_path does not exist or cannot be found')
ConnectionError: socket_path does not exist or cannot be found

fatal: [sw-06.us01]: FAILED! => {}

MSG:

Unexpected failure during module execution.

	to retry, use: --limit @/Users/maxx/TK/ansible/dell-switches/mve-pre-bonding.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
sw-06.us01                 : ok=2    changed=1    unreachable=0    failed=1


# maxx @ MacBook-Pro-2 in ~/TK/ansible/dell-switches on git:master x [13:52:32] C:2
```

Switch details:
```
sw-06# show version
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2018 by Dell Inc. All Rights Reserved.
OS Version: 10.4.0E(R3)
Build Version: 10.4.0E(R3.233)
Build Time: 2018-03-30T18:05:41-0700
System Type: S4148F-ON
Architecture: x86_64
Up Time: 1 week 5 days 21:01:55
```

What could be the cause of this, and how could I fix it?

Thank you for your help in this!

**Comment by skg-net** [comment]
@mvernimmen Thanks for reporting the issue, we will get back.

**Comment by abirami-n** [comment]
@mvernimmen The error "socket_path does not exist or cannot be found", pops up when, the device reload happens on any ssh session in the same time while the playbook run is in progress.
We weren't able to reproduce this in other cases. Let us know if you have any queries.

**Comment by ronnyaa** [comment]
Did you ever find a solution to this poroblem ? 
I am experiencing something similar now when i try to deploy a few thousand vlans across the ports of our S5248F-ON switches.
